title: Harry Badland
email: your.email@example.com
description: >-
  BSc Chemistry graduate exploring the intersection of computational chemistry 
  and machine learning. Specializing in neural network potentials, molecular 
  dynamics, and research software development.

tagline: "Chemistry Graduate • Machine Learning Enthusiast • Computational Researcher"
keywords: "computational chemistry, machine learning, neural networks, molecular dynamics, python, research"

author:
  name: Harry Badland
  email: your.email@example.com
  bio: "BSc Chemistry graduate with a passion for computational chemistry and machine learning"
  location: "London, UK"
  education: "BSc Chemistry, Cardiff University"
  
baseurl: ""
url: "https://hbadland.github.io" 
github_username: hbadland
linkedin_username: harry-badland-099517237

social:
  github: https://github.com/hbadland
  linkedin: https://www.linkedin.com/in/harry-badland-099517237/
  email: your.email@example.com

cv_url: "./assets/CV.pdf"
portfolio_url: "https://github.com/hbadland"

timezone: Europe/London
encoding: "utf-8"
markdown: kramdown
highlighter: rouge
permalink: pretty

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - README.md
  - LICENSE
  - CNAME

include:
  - _pages

collections:
  projects:
    output: true
    permalink: /:collection/:name/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      author: "Harry Badland"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"

lang: en_GB
locale: en_GB

show_excerpts: true
excerpt_separator: <!--more-->

navigation:
  - title: Home
    url: /
  - title: About
    url: /#about
  - title: Skills
    url: /#skills
  - title: Projects
    url: /#projects
  - title: Contact
    url: /#contact

featured_projects:
  - name: "TorchMD-NET Neural Potentials"
    description: "Neural network potentials for molecular dynamics simulations"
    url: "https://github.com/hbadland/torchmd-net"
    tech: ["PyTorch", "Python", "Neural Networks"]
    
  - name: "Invisibility Cloak"
    description: "Computer vision project with real-time processing"
    url: "https://github.com/hbadland/invisibility-cloak"
    tech: ["Python", "OpenCV", "Computer Vision"]

skills:
  machine_learning:
    name: "Machine Learning"
    icon: "fas fa-brain"
    technologies: ["PyTorch", "TensorFlow", "Scikit-learn", "Neural Networks"]
    
  computational_chemistry:
    name: "Computational Chemistry"
    icon: "fas fa-flask"
    technologies: ["Molecular Dynamics", "TorchMD-NET", "Quantum Chemistry"]
    
  programming:
    name: "Programming"
    icon: "fas fa-code"
    technologies: ["Python", "Jupyter", "NumPy/SciPy", "Pandas"]
    
  data_analysis:
    name: "Data Analysis"
    icon: "fas fa-chart-line"
    technologies: ["Matplotlib", "Seaborn", "Statistical Analysis"]

contact:
  email: your.email@example.com
  linkedin: https://www.linkedin.com/in/harry-badland-099517237/
  github: https://github.com/hbadland
  location: "London, UK"

professional_summary: >-
  BSc Chemistry graduate from Cardiff University with a passion for bridging 
  computational chemistry and machine learning. Experience working with neural network 
  potentials, molecular dynamics simulations, and interested in research software 
  that makes complex chemistry more accessible.

# Site Footer
footer_text: "© 2025 Harry Badland. Combining the precision of chemistry with the power of computation."
